### ISSUE TITLE
add support for promoting/ demoting users.

### ISSUE THREAD

**Issue by benioriginal** [italoseara/whatsappy#19]
I know it's hard but please! 
also where can I donate? :3

**Comment by italoseara** [comment]
I'll be on vacation this weekend, but I can do this by monday, and thank you for the donation offer. I'll add a PayPal link to the Readme for those who want to support the project.

My PayPal is italo.sseara@gmail.com, BTW. I'll be pleased with any amount to support this project, and thank you again for the offer.

**Comment by benioriginal** [comment]
Sure, I have just finished my own whatsapp api and bot. Also I can't send you nothing, I get an error saying "Your recipient can't accept payments right now"

**Comment by italoseara** [comment]
I'll need a moment to implement the changes because of my college, but it wont take long, also, you couldn't send anything because I didn't finish the confirmation process, I'm sorry for that, it will take a while to confirm, but I'll update you in the situation. Thanks again for the support.

**Comment by italoseara** [comment]
Paypal says it is all good now, you can try again, if you want to.

**Comment by italoseara** [comment]
I'm sorry that it took so long for me to respond, but I just updated the library and added this feature, there are some problems that i need to take care still, but it's usable for now.
