### ISSUE TITLE
Can't login, writes update google chrome

### ISSUE THREAD

**Issue by Duckduckgot** [italoseara/whatsappy#2]
On Windows 10 x64
after running the script, update the chrome browser.
But I am using the latest version. Launched with visible = True and False, the result is the same.
![whatsappy](https://user-images.githubusercontent.com/49223254/112420489-a2ac8180-8d70-11eb-8545-b135b41d3441.JPG)

**Comment by italoseara** [comment]
it shouldn't happen when you put visible = True, are you using Linux?

**Comment by Duckduckgot** [comment]
No, Windows 10.
Solved my problem, the problem was user agent --headless.
Headless mode is bad, very bad because in this mode there is no access to the system clipboard.

**Comment by italoseara** [comment]
> No, Windows 10.
> Solved my problem, the problem was user agent --headless.
> Headless mode is bad, very bad because in this mode there is no access to the system clipboard.

alright, mine works just fine, i'll commit a new version, you can download it and change it again

**Comment by italoseara** [comment]
i know it's been some time since my last update, i had no time to do it, but i just solved it
