### ISSUE TITLE
Change default value for `visible` option on `Whatsapp.login`

### ISSUE THREAD

**Issue by yohannd1** [italoseara/whatsappy#4]
It seems this library doesn't work on linux yet. I'm still figuring out why, though.

**Comment by yohannd1** [comment]
Found the issue! It wasn't really a code bug (or even a linux issue), but rather [a bad default option](https://github.com/italoseara/whatsappy/blob/f4917970ffb136f14defd3ede515c90e0913dcbb/whatsappy/login.py#L37):

```python
def login(self, visible: bool = False, timeout: int = 60):
```

For a starter, trying to login, no matter what browser is being used, might end up with a frozen session. That happens because they didn't set `visible` to true, and they won't log in automatically.

The best to do here is to set the default value of `visible` to `True`. We could also find some way to error out when the window is not visible and the login was not done yet, but I'm not very familiar with JS so I can't help with that :')

**Comment by italoseara** [comment]
thanks for the tip, it will be updated on the next version
