### ISSUE TITLE
cant login, whatsapp web hangs

### ISSUE THREAD

**Issue by KleanOcean** [italoseara/whatsappy#8]
once i run the code, the log in part hanged and cant further proceed, is the code working now?

**Comment by italoseara** [comment]
does it raise any errors? 
have you tried using `whatsapp.login(visible=True)` to see what's happening?

**Comment by italoseara** [comment]
as it is the first time of you using it, it may take a while to load, as the new whatsapp update forces you to download all the conversations you have, it happened to me too a while ago, but as soon as the download had finished, it came back to normal

**Comment by KleanOcean** [comment]
Thanks, it works now, i previously cannot login due to the multi device setting, once i switch it off, yr code works!
