### ISSUE TITLE
SyntaxError: invalid syntax (main)

### ISSUE THREAD

**Issue by JonasCardoso** [italoseara/whatsappy#9]
i tried use code exp, but i got this error, i forget something?

Traceback (most recent call last):
  File "zap.py", line 1, in <module>
    from whatsappy import Whatsapp
  File "/home/jonas/.local/lib/python3.8/site-packages/whatsappy/__init__.py", line 1, in <module>
    from .main import Whatsapp
  File "/home/jonas/.local/lib/python3.8/site-packages/whatsappy/main.py", line 591
    match __name:
          ^
SyntaxError: invalid syntax

```
from whatsappy import Whatsapp

whatsapp = Whatsapp()

whatsapp.login(visible=False) # Login whatsapp (Headless mode)

chat = whatsapp.chat('Mom') # Goes to the selected chat
chat.send('Hello') # Send a message

whatsapp.close() # Exit
```

**Comment by italoseara** [comment]
you need to have python 3.10 to run it, it seams like you still are in python 3.9, that's why match case doesn't work

**Comment by yohannd1** [comment]
Talking about that, I think we could add something to verify that and give an error message in case the wrong versin is being used. I think I know how to do it so I may help soon with it.

**Comment by italoseara** [comment]
> Talking about that, I think we could add something to verify that and give an error message in case the wrong versin is being used. I think I know how to do it so I may help soon with it.

I think there is some way to make it not able to install if it's not 3.10 or above, I'll try to find it
